### ISSUE TITLE
Consider taking advantage of this list of task/step types when qualifying event types

### ISSUE THREAD

**Issue by amfred** [cdevents/spec#18]
See: https://github.com/cdfoundation/sig-interoperability/pull/81 

In the working [Event Vocabulary document](https://hackmd.io/lBlDCrL7TvmtNOjxdopJ5g#Events-Categories) under ["Events Categories"(https://hackmd.io/lBlDCrL7TvmtNOjxdopJ5g) we have a list of event types.  Consider using the same terminology as that proposed for the Interoperability SIG's CI/CD Vocabulary. 

For example, you have "Build", "Test", and "Release" events, while the Interoperability SIG vocabulary document has "Build", "Test", "Publish" and "Deploy".  ("Release" can mean "Publish" and/or "Deploy" depending on who's using the term.)

**Comment by m-linner-ericsson** [comment]
Good point we will look into this

**Comment by m-linner-ericsson** [comment]
That document is rather old. We now have the spec on https://cdevents.dev/docs/.

**Comment by amfred** [comment]
The PRs with the terminology have been merged now, see: https://github.com/cdfoundation/sig-interoperability/blob/master/docs/vocabulary.md#mapping-of-terms, https://github.com/cdfoundation/sig-interoperability/blob/master/docs/vocabulary.md#stages and https://github.com/cdfoundation/sig-interoperability/blob/master/docs/vocabulary.md#pipeline-step-types

**Comment by e-backmark-ericsson** [comment]
@amfred, as you were looking at an old document when creating this issue, do you think it is still valid? I believe the terms are now at least more or less up-to-date and aligned with the steps defined in sig-interop.

**Comment by e-backmark-ericsson** [comment]
It struck me that we should probably rename our TaskRun events to become Step events instead, if we should follow that vocabulary. And we should probably add corresponding Stage events as well.

**Comment by e-backmark-ericsson** [comment]
I believe we should be aligned with this terminology already for our release 0.1, to not introduce too many non-backwards compliant changes later

**Comment by amfred** [comment]
A Step in the vocabulary I worked on would map to a Tekton TaskRun.
Example: 
```
  tasks:
    - name: setup-init
      params:
        - name: image-url
          value: "$(params.output-image)"
      taskRef:
        name: init
    - name: source-clone-repository
      runAfter:
        - setup-init
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: "$(params.revision)"
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
        - name: basic-auth
          workspace: git-auth
    - name: build-configure-build
      runAfter:
        - source-clone-repository
      taskRef:
        name: configure-build
      workspaces:
        - name: source
          workspace: workspace
        - name: registry-auth
          workspace: registry-auth
    - name: secret-detection-detect-secrets
      taskRef:
        name: utils-task
      runAfter:
        - source-clone-repository
      params:
        - name: SCRIPT
          value: |
            #!/usr/bin/env bash
            echo "This is a placeholder for secret-detection-detect-secrets"
```

I think of Stages as being implemented by collections of TaskRuns in the Tekton world.  Stages are more abstract and can be implemented by a single pipeline, a portion of a single pipeline, multiple pipelines, or portions of multiple pipelines.   People talk about them all the time in talks and articles, but in reality, they're pretty complex.
